id: PYSEC-2019-246
modified: 2024-11-21T14:22:49.597801Z
published: 2019-07-28T19:15:00Z
aliases:
- CVE-2019-14370
details: In Exiv2 0.27.99.0, there is an out-of-bounds read in Exiv2::MrwImage::readMetadata()
  in mrwimage.cpp. It could result in denial of service.
affected:
- package:
    ecosystem: PyPI
    name: exiv2
    purl: pkg:pypi/exiv2
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
  versions:
  - "0.1"
  - 0.11.0
  - 0.11.1
  - 0.11.2
  - 0.11.3
  - 0.12.0
  - 0.12.1
  - 0.13.0
  - 0.13.1
  - 0.13.2
  - 0.14.0
  - 0.14.1
  - 0.15.0
  - 0.16.0
  - 0.16.1
  - 0.16.2
  - 0.16.2.post1
  - 0.16.3
  - 0.16.3.post1
  - 0.17.0
  - 0.17.1
  - "0.2"
  - "0.3"
  - 0.3.1
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
references:
- type: EVIDENCE
  url: https://github.com/Exiv2/exiv2/issues/954
- type: REPORT
  url: https://github.com/Exiv2/exiv2/issues/954
- type: ARTICLE
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2023/01/msg00004.html
