affected:
- package:
    ecosystem: PyPI
    name: exiv2
    purl: pkg:pypi/exiv2
  ranges:
  - events:
    - introduced: '0'
    type: ECOSYSTEM
  versions:
  - '0.1'
  - 0.11.0
  - 0.11.1
  - 0.11.2
  - 0.11.3
  - 0.12.0
  - 0.12.1
  - 0.13.0
  - 0.13.1
  - 0.13.2
  - 0.14.0
  - 0.14.1
  - 0.15.0
  - 0.16.0
  - 0.16.1
  - 0.16.2
  - 0.16.2.post1
  - 0.16.3
  - 0.16.3.post1
  - 0.17.0
  - 0.17.1
  - '0.2'
  - '0.3'
  - 0.3.1
aliases:
- CVE-2017-11337
details: There is an invalid free in the Action::TaskFactory::cleanup function of
  actions.cpp in Exiv2 0.26. A crafted input will lead to a remote denial of service
  attack.
id: PYSEC-2017-119
modified: '2024-11-21T14:22:46.232444Z'
published: '2017-07-17T13:18:00Z'
references:
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1470737
severity:
- score: CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
  type: CVSS_V3
withdrawn: '2024-11-22T04:37:03Z'
