affected:
- package:
    ecosystem: PyPI
    name: capstone
    purl: pkg:pypi/capstone
  ranges:
  - events:
    - introduced: '0'
    - fixed: 87a25bb543c8e4c09b48d4b4a6c7db31ce58df06
    repo: https://github.com/capstone-engine/capstone
    type: GIT
  - events:
    - introduced: '0'
    type: ECOSYSTEM
  versions:
  - '2.0'
  - '2.1'
  - '3.0'
  - 3.0.1
  - 3.0.2
  - 3.0.3
  - 3.0.4
  - 3.0.5
  - 3.0.5.post1
  - 3.0.5rc2
  - 4.0.0
  - 4.0.1
  - 4.0.2
  - 5.0.0
  - 5.0.0.post1
  - 5.0.0rc2
  - 5.0.0rc4
  - 5.0.1
  - 5.0.2
  - 5.0.3
  - 6.0.0a1
aliases:
- CVE-2016-7151
details: Capstone 3.0.4 has an out-of-bounds vulnerability (SEGV caused by a read
  memory access) in X86_insn_reg_intel in arch/X86/X86Mapping.c.
id: PYSEC-2019-242
modified: '2024-11-21T14:22:41.553247Z'
published: '2019-05-15T14:29:00Z'
references:
- type: EVIDENCE
  url: https://github.com/aquynh/capstone/pull/725
- type: WEB
  url: https://github.com/aquynh/capstone/pull/725
- type: FIX
  url: https://github.com/aquynh/capstone/commit/87a25bb543c8e4c09b48d4b4a6c7db31ce58df06
severity:
- score: CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
  type: CVSS_V3
withdrawn: '2024-11-22T04:37:03Z'
