affected:
- package:
    ecosystem: PyPI
    name: pg-query
    purl: pkg:pypi/pg-query
  ranges:
  - events:
    - introduced: '0'
    - fixed: '0.28'
    type: ECOSYSTEM
  versions:
  - '0.1'
  - '0.10'
  - '0.11'
  - '0.12'
  - '0.13'
  - '0.14'
  - '0.15'
  - '0.16'
  - '0.17'
  - '0.18'
  - '0.19'
  - '0.2'
  - '0.20'
  - '0.21'
  - '0.22'
  - '0.23'
  - '0.24'
  - '0.25'
  - '0.26'
  - '0.27'
  - '0.3'
  - '0.4'
  - '0.5'
  - '0.6'
  - '0.7'
  - '0.8'
  - '0.9'
aliases:
- CVE-2018-18482
- GHSA-vm3q-58wm-2r2x
details: An issue was discovered in libpg_query 10-1.0.2. There is a memory leak in
  pg_query_raw_parse in pg_query_parse.c, which might lead to a denial of service.
id: PYSEC-2018-154
modified: '2024-11-25T18:35:18.357593Z'
published: '2018-10-18T18:29:00Z'
references:
- type: EVIDENCE
  url: https://github.com/lfittl/libpg_query/issues/49
- type: REPORT
  url: https://github.com/lfittl/libpg_query/issues/49
severity:
- score: CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
  type: CVSS_V3
