id: PYSEC-0000-CVE-2016-1242
severity:
- type: CVSS_V3
  score: CVSS:3.0/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N
details: file_open in Tryton before 3.2.17, 3.4.x before 3.4.14, 3.6.x before 3.6.12,
  3.8.x before 3.8.8, and 4.x before 4.0.4 allows remote authenticated users with
  certain permissions to read arbitrary files via the name parameter or unspecified
  other vectors.
affected:
- package:
    name: tryton
    ecosystem: PyPI
    purl: pkg:pypi/tryton
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 3.2.17
references:
- type: REPORT
  url: https://bugs.tryton.org/issue5808
- type: ADVISORY
  url: http://www.debian.org/security/2016/dsa-3656
- type: ADVISORY
  url: http://www.tryton.org/posts/security-release-for-issue5795-and-issue5808.html
aliases:
- CVE-2016-1242
modified: "2017-01-13T02:59:00Z"
published: "2016-09-07T19:28:00Z"
